#!/usr/bin/env Rscript
# -*-coding: utf-8 -*-
#-----------------------------------------------
# Title: Helper function to save plots as both PDF and PNG
# Author: Amanda Zacharias
# Date: 2025-09-04
# Email: 16amz1@queensu.ca
# Notes -----------------------------------------------
# module load StdEnv/2023 r/4.5.0

# Options -----------------------------------------------

# Packages -----------------------------------------------
library(ggplot2)
# Source -----------------------------------------------

# Code -----------------------------------------------
save_plot <- function(
  plot_obj, new_filename, new_path, w = 180, h = 180, unit = "mm", resolution = 400
) {
  #' Save a ggplot object as both PDF and PNG
  #'
  #' This function saves a ggplot2 plot object to PDF and PNG formats in the specified directory.
  #' The PNG filename is taken from `new_filename`, and the PDF filename is
  #'  generated by removing the extension from `new_filename` and appending ".pdf".
  #'
  #' @param plot_obj ggplot object to save
  #' @param new_filename Filename for the PNG (should end with .png)
  #' @param new_path Directory to save the files
  #' @param w Width of the plot (default: 180)
  #' @param h Height of the plot (default: 180)
  #' @param unit Units for width/height (default: "mm")
  #' @param resolution Resolution for PNG (default: 400)
  #' @return No return value; files are saved to disk
  #' @examples
  #' save_plot(p, "myplot.png", "plots/")
  #' save_plot(p, "figure.png", "results/", w = 200, h = 150)
  # Save as PDF
  ggsave(
    plot = plot_obj,
    filename = sprintf("%s.pdf", tools::file_path_sans_ext(new_filename)),
    path = new_path,
    width = w,
    height = h,
    units = unit
  )
  # Save as PNG
  ggsave(
    plot = plot_obj,
    filename = sprintf("%s.png", tools::file_path_sans_ext(new_filename)),
    path = new_path,
    width = w,
    height = h,
    units = unit,
    dpi = resolution
  )
}